### ISSUE TITLE
ManagementService jwt expiring

### ISSUE THREAD

**Issue by pnts-se** [edumeet/edumeet-room-server#58]
Got this error message suddenly when trying to join a room:

```
2023-06-29T12:32:13.775Z edumeet:DEBUG:Peer addConnection()
2023-06-29T12:32:13.775Z edumeet:DEBUG:Room addPeer() [id: f01c5f67-e80e-4b79-b6de-848e35ecee15]
2023-06-29T12:33:17.975Z edumeet:DEBUG:SocketIOConnection "request" event [request: { method: 'updateToken', data: { token: 'eyJhbGci.............................' } }]
2023-06-29T12:33:17.975Z edumeet:DEBUG:Peer request() unhandled request [method: updateToken]
2023-06-29T12:33:35.806Z edumeet:WARN:socketHandler handleConnection() [error: Error: Invalid token at ServerManager.handleConnection (/usr/src/app/dist/src/ServerManager.js:57:23) at descriptor.value (/usr/src/app/node_modules/edumeet-common/lib/decorators.js:21:30) at Namespace.socketHandler (/usr/src/app/dist/src/common/socketHandler.js:15:23) at Namespace.emit (node:events:513:28) at Namespace.emit (node:domain:489:12) at Namespace.emitReserved (/usr/src/app/node_modules/socket.io/dist/typed-events.js:56:22) at Namespace._doConnect (/usr/src/app/node_modules/socket.io/dist/namespace.js:269:14) at /usr/src/app/node_modules/socket.io/dist/namespace.js:231:22 at process.processTicksAndRejections (node:internal/process/task_queues:77:11)]
2023-06-29T12:33:35.804Z edumeet:DEBUG:socketHandler socket connection [socketId: 9HEgJkUX5yexR2UGAACa, roomId: wp4t2, peerId: f01c5f67-e80e-4b79-b6de-848e35ecee15, tenantId: 1]
```

Restart of room-server service fixed the issue. Somehow the room-server got itself into a state where it was not updating tokens in a correct way. Must investigate further.

**Comment by pnts-se** [comment]
Seems we get stuck waiting for mgmt service in:
`edumeet:DEBUG:Room addPeer()`

`edumeet:DEBUG:ManagementService getRoom()` is not called successfully.

**Comment by pnts-se** [comment]
We do not renew the jwt used when talking to the mgmt service.
Thus, it expires and that's the issue.
